### ISSUE TITLE
[User Story] Messaging and Group Chat in the Same role Epic 2

### ISSUE THREAD

**Issue by Jiawei-liao-002481222** [INEEDAMONITOR/Role-Rally#19]
## User Story #3

As a user, I want to send messages to my friends and have the ability to create group chats with friends in the same role.

## Detailed Description

Enabling users to engage in messaging and group chats strictly within the confines of their designated roles, ensuring that all communications are contained and relevant to the specific role context they are part of, thereby enhancing privacy and interaction relevance.

## Acceptance Criteria

-   [x] #34
-   [x] #35
-   [x] #36

**Comment by RuizheZengNEU** [comment]
SendBird Chat API Demo #11
