### ISSUE TITLE
[User Story] Create, Edit, and Delete Roles Epic 1

### ISSUE THREAD

**Issue by Jiawei-liao-002481222** [INEEDAMONITOR/Role-Rally#5]
## User Story #2 

 As a user, I want the ability to create, edit, and delete different roles on my account, customize their names, profile pictures, and settings, and manage them easily from my profile settings.

## Detailed Description

This user story focuses on empowering users with the flexibility to curate their digital presence through role management within a chat application.
It aims to allow users to create, edit, and delete roles, each with customized names, profile pictures, and settings, directly from their profile settings. 
This feature addresses the need for users to navigate different social contexts seamlessly, by presenting the most appropriate digital identity for each scenario, whether it be professional, personal, or social. 
The implementation will involve designing a user-friendly interface for role management, developing backend support for these operations, and ensuring security and privacy are maintained throughout the process.

## Acceptance Criteria

-   [x] #24
-   [x] #26
-   [ ] #28
-   [x] #27

**Comment by INEEDAMONITOR** [comment]
Database part ready for API dev #21

**Comment by CKYWEB** [comment]
- Accessibility of the profile
    Make another document for accessibility
- When created a new user
    User has to finish the process of building a role with a profile, otherwise we don't want the user to get in the main page

**Comment by junweid62** [comment]
good
